# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from ScreenShot import get_title, download_youtube, create_screenshots, delete_intro,\
                                 delete_duplicates, create_word, delete_everything
import sys
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(518, 582)
        MainWindow.setStyleSheet("background-color: #211f1c;")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        MainWindow.setWindowIcon(QtGui.QIcon("note_audio_music_3097.ico"))
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(21, 21, 134, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet(
            "QLabel\n"
            "\n"
            "{\n"
            "    color: #c78d36;\n"
            '    font: 14pt "Times New Roman";\n'
            "}"
        )
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 50, 481, 41))
        self.textEdit.setStyleSheet(
            "QTextEdit\n"
            "{\n"
            "    color:#c2ab84;\n"
            "    \n"
            '    font: 14pt "Times New Roman";\n'
            "}"
        )
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 481, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(
            "QLabel\n"
            "\n"
            "{\n"
            "    color: #c78d36;\n"
            '    font: 14pt "Times New Roman";\n'
            "}"
        )
        self.label_2.setObjectName("label_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 133, 481, 41))
        self.textEdit_2.setText("300")
        self.textEdit_2.setStyleSheet(
            "QTextEdit\n"
            "{\n"
            "    color:#c2ab84;\n"
            "    \n"
            '    font: 14pt "Times New Roman";\n'
            "}"
        )
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 182, 458, 80))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(
            "QLabel\n"
            "\n"
            "{\n"
            "    color: #c78d36;\n"
            '    font: 14pt "Times New Roman";\n'
            "}"
        )
        self.label_3.setObjectName("label_3")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 269, 481, 41))
        self.textEdit_3.setStyleSheet(
            "QTextEdit\n"
            "{\n"
            "    color:#c2ab84;\n"
            "    \n"
            '    font: 14pt "Times New Roman";\n'
            "}"
        )
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 318, 93, 35))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(
            "QPushButton\n"
            "{\n"
            "    color: #c78d36;\n"
            '    font: 14pt "Times New Roman";\n'
            "    background-color: #302d27;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "     background-color: #47423a;\n"
            " }"
        )
        self.pushButton.setDefault(True)
        self.pushButton.setAutoDefault(True)
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 360, 481, 191))
        self.listWidget.setObjectName("listWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.listWidget.setStyleSheet(
            "QListWidget\n{\ncolor: #c2ab84;\nfont: 12pt Times New Roman;\n}"
        )
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NotesStealer 2.0"))
        self.label.setText(_translate("MainWindow", "Введите URL."))
        self.label_2.setText(
            _translate("MainWindow", "Выберите интервал съемки скриншотов (кадры).")
        )
        self.label_3.setText(
            _translate(
                "MainWindow",
                "Введите координаты прямоугольника с нотами\n"
                'в формате "ya,yb,xa,xb".\n'
                "Не вводите, если SkyGuitar-red-like.",
            )
        )
        self.pushButton.setText(_translate("MainWindow", "Ввод"))
        self.pushButton.clicked.connect(self.steal_notes)

    def steal_notes(self):
        red = False
        yellow = False
        self.listWidget.clear()
        url = self.textEdit.toPlainText()
        interval = int(self.textEdit_2.toPlainText())
        res = self.textEdit_3.toPlainText()
        res = res.split(",")
        square = []
        if len(res) > 1:
            square = [int(i) for i in (res)]
        if (len(res) == 1) & ("SkyGuitar" in url):
            red = True
        title_quality = get_title(url)
        correct_title = title_quality[0]
        quality = title_quality[1]
        self.listWidget.addItem(correct_title)
        self.listWidget.addItem("Качество: " + str(quality))
        delete_everything(correct_title)
        download_youtube(url, correct_title)
        num_of_screens = create_screenshots(correct_title, interval, square)
        self.listWidget.addItem("Количество скриншотов: " + str(num_of_screens))
        if (square == [0, 335, 0, 1370]) and ("SkyGuitar" in url):
            yellow = True
        if red or yellow:
            delete_intro(num_of_screens, correct_title, yellow)
            delete_duplicates(correct_title, yellow)
        self.listWidget.addItem(
            "Количество сохраненных скриншотов: "
            + str(len(os.listdir("./" + correct_title + "/Screenshots/")))
        )
        create_word(correct_title, num_of_screens)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
